AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  Exclude:
    - "spec/fixtures/**/*"

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Max: 80

Metrics/MethodLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
